// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset } from '../storyblok.d.ts';
export interface Page {
  body?: (Page | SeoPage)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SeoPage {
  siteName?: string;
  ogImage?: StoryblokAsset;
  component: "seoPage";
  _uid: string;
  [k: string]: unknown;
}
